<?php
/*
 * DeDS Client - Device Detection Service module for Drupal 6
 * Copyright (C) 2011 Catalyst IT
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @file
 * https://github.com/jkyamog/DeDS
 * @author Ben Bradshaw - ben@catalyst.net.nz
 */

/**
 * Implementation of hook_menu().
 */
function deds_client_menu() {
  $items['admin/settings/deds-client'] = array(
    'title' => 'Device Detection Service',
    'description' => 'Configure your DeDS URL and cache lifetime',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('deds_client_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'deds_client.admin.inc',
  );
  return $items;
}

/*
 * Constructor for DeDS client
 */
function deds_client_get_client() {
  $api_uri = variable_get('deds_client_api_uri', '');
  $cache_lifetime = variable_get('deds_client_cache_time', '');

  if (empty($api_uri)) {
    watchdog('deds_client', 'The DeDS API URI has not been configured. Please visit the configuration page.' . ' ' . l('Configure DeDS Module', '/admin/settings/deds-client'));
    //drupal_set_message(t('Unable to connect to Sailthru, please check your settings'), 'error', false);
    return FALSE;
  }
  if (empty($cache_lifetime)) {
    watchdog('deds_client', 'The Sailthru API Secret has not been configured. Please visit the configuration page.' . ' ' . l('Configure Sailthru Module', '/admin/settings/sailthru-client'));
    //drupal_set_message(t('Unable to connect to Sailthru, please check your settings'), 'error', false);
    return FALSE;
  }

  module_load_include('inc', 'deds_client', 'includes/DedsClient');

  return new DedsClient($api_uri, $cache_lifetime);
}
